sudo: false

language: php

matrix:
  include:
    - php: 5.6
    - php: 7
    - php: hhvm
    
install:
  - travis_retry composer install --no-interaction
  
script:
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover ./clover.xml