sudo: false

language: php

matrix:
  include:
    - php: 5.6
      env:
        - EXECUTE_CS_CHECK=true
    - php: 7
    - php: hhvm

install:
  - travis_retry composer install --no-interaction

script:
  - ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./clover.xml
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run ; fi

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover ./clover.xml